version: '3.6'

services:
  app.web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        env: prod
    networks:
        - webnet
  app.sandbox:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        env: snadbox
    networks:
        - webnet
networks:
  webnet:

