version: '3.6'

services:
  app.web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        env: prod
      volumes:
        - .:/app
    networks:
        - webnet
networks:
  webnet:
