version: '3.6'

services:
  sandbox.web:
    build:
      context: .
      args:
        env: sandbox
    ports:
      - "8080:80"
  app.web:
    build:
      context: .
      args:
        env: prod
    ports:
      - "8081:80"

