version: '3.6'

services:
  app.web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        env: prod
        configuration: production
    networks:
        - webnet
  app.sandbox:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        env: dev
        configuration: sandbox
    networks:
        - webnet
networks:
  webnet:

