// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  appTitle: 'GenLead Pro',
  production: true,
  envName: 'PROD',
  version: env.npm_package_version,
  serverUrl: '/api',
  authEndpoint: 'http://genleadpro.com:8000/api/auth',
  apiEndpoint: 'http://genleadpro.com:8000/api/v1',
  apiProtocol: 'http', // or 'https'
  apiPort: '8000', // used to compose tenant api end point
  apiPath: '/api/v1', // used to compose tenant api end point
  whiteLists: ["genleadpro.com:8000", "genleadpro.com"]
};
